_format_version: "2.1"

services:
  - name: my-service
    url: http://httpbin.org/anything
    plugins:
      - name: kong-plugin-myplugin
    routes:
      - name: get-post-data
        methods: [GET, POST]
        paths: [/v1/my-plugin-data]
